export { TechCreateResolver } from './creation'
export { TechQueryResolver } from './query'
export { TechDeleteResolver } from './delete'
export { CreateTechInProjResolver } from './create-techInProj'
export { DeleteTechsInProjResolver } from './delTechInProj'
export { TechStackModResolvers } from './mod'
